[general]
# Log messages of level equal to or above the specified level are
# printed out. Supported levels are "debug", "info", "warning", "error"
# and "critical" (ordered from lowest to highest level).
# Default: "info"
#
#log = "info"

[key]
# Assign actions to the buttons of the controller.
#
# An action consists of type and content, separated by a colon ":". It
# is written in the form
#     <type>:<content>
#
# There are several types of actions: "key", "command", "cursor_up",
# "cursor_down", "cursor_left", "cursor_right".
#
# "key" action:
# The content part is a key name of the keyboard. That key will be
# triggered when you press the controller button. For example, if you
# set `a = "key:KEY_ESC"`, then the ESC key will be triggered when you
# press the "A" button on the controller. The available names of keys
# are listed in [1] with the name started with `KEY_` or `BTN_`.
# [1] https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h
#
# "command"" action:
# The content part is a command that will be executed when you press the
# controller button. If you set `b = "command:touch ~/file.txt"`, then
# the command "touch ~/file.txt" will be triggered when you press the
# "B" button of the controller.
#
# "cursor_up", "cursor_down", "cursor_left", "cursor_right" action:
# The content part is a non-negative integer. The cursor will move
# in the corresponding direction by the specified number of pixels.
#
# Default: "" (No acttion is assigned.)
#
#up =""
#down =""
#left =""
#right =""
#a = ""
#b = ""
#x = ""
#y = ""
#l = ""
#r = ""
#zl = ""
#zr = ""
#plus = ""
#minus = ""
#capture = ""
#home = ""
#left_analog_press = ""
#right_analog_press = ""

[analog]
# Assign actions to the analog sticks of the controller. Set it to
# "cursor", then the analog stick controls the mouse cursor. Set it to
# "wheel", then the analog stick controls the mouse wheel.
#
#left_analog = "mouse"
#right_analog = "wheel"

[options]
# Revert the horizontal scrolling direction
# Default: false
#
#revert_scroll_x = false

# Revert the vertical scrolling direction
# Default: false
#
#revert_scroll_y = false
